import { Interface } from './interface';

export const CUSTOMERS: Interface[] = [
  { id: 1, name: 'Customer 1',address:'Uiversity',email:'customer1@gmail.com',mobile:1234567, 
  array:[
    {
    id:1,
    orderName:'order1',
    quantity:5,
    orderNum:464574
  },
  {
    id:2,
    orderName:'order2',
    quantity:5,
    orderNum:4
  },
  {
    id:3,
    orderName:'order3',
    quantity:5,
    orderNum:42356
  },
  {
    id:4,
    orderName:'order4',
    quantity:5,
    orderNum:4456457
  }
]
},
  { id: 2, name: 'Customer 2',address:'Uiversity',email:'customer2@gmail.com',mobile:1234567890,
  array:[
    {
      id:1,
      orderName:'order4',
      quantity:5,
      orderNum:464574
    },
    {
      id:2,
      orderName:'order5',
      quantity:5,
      orderNum:4
    },
    {
      id:3,
      orderName:'order6',
      quantity:5,
      orderNum:42356
    },
    {
      id:4,
      orderName:'order7',
      quantity:5,
      orderNum:4456457
    }

]
},
  { id: 3, name: 'Customer 3',address:'Uiversity',email:'customer3@gmail.com',mobile:123456,
  array:[
    {
      id:1,
      orderName:'order8',
      quantity:5,
      orderNum:464574
    },
    {
      id:2,
      orderName:'order9',
      quantity:5,
      orderNum:4
    },
    {
      id:3,
      orderName:'order10',
      quantity:5,
      orderNum:42356
    },
    {
      id:4,
      orderName:'order11',
      quantity:5,
      orderNum:4456457
    }

]
 }
];;
